trigger:
- master
# define the VM agent pool Name
pool:
  name: 'govpool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acrRKS-service-connection'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aksRKS-service-connection'
    azureResourceGroup: 'private-aks-RG'
    kubernetesCluster: 'private-aks-cls'
    command: 'apply'
    arguments: '-f deploy.yaml'
