trigger:
- none
# define the VM agent pool Name
pool:
  name: 'govpool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acrRKS-service-connection'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'MS_SI_INTERNAL_SUBS (2b2bb6af-68a3-4419-af72-5ba0de5312e8)'
    azureResourceGroup: 'private-aks-RG'
    kubernetesCluster: 'private-aks-cls'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

